// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vynel/node/v1/node.proto

// Panel <-> node protocol (docs/ARCHITECTURE.md §14).
// The node dials the panel; the panel pushes desired state, the node acknowledges.

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeGateway_Join_FullMethodName    = "/vynel.node.v1.NodeGateway/Join"
	NodeGateway_Connect_FullMethodName = "/vynel.node.v1.NodeGateway/Connect"
)

// NodeGatewayClient is the client API for NodeGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeGatewayClient interface {
	// One-time registration with an install token (server-auth TLS with a pinned CA, no client cert).
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// Main channel (mTLS with the certificate obtained from Join).
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, PanelMessage], error)
}

type nodeGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeGatewayClient(cc grpc.ClientConnInterface) NodeGatewayClient {
	return &nodeGatewayClient{cc}
}

func (c *nodeGatewayClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, NodeGateway_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, PanelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeGateway_ServiceDesc.Streams[0], NodeGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, PanelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeGateway_ConnectClient = grpc.BidiStreamingClient[NodeMessage, PanelMessage]

// NodeGatewayServer is the server API for NodeGateway service.
// All implementations must embed UnimplementedNodeGatewayServer
// for forward compatibility.
type NodeGatewayServer interface {
	// One-time registration with an install token (server-auth TLS with a pinned CA, no client cert).
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// Main channel (mTLS with the certificate obtained from Join).
	Connect(grpc.BidiStreamingServer[NodeMessage, PanelMessage]) error
	mustEmbedUnimplementedNodeGatewayServer()
}

// UnimplementedNodeGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeGatewayServer struct{}

func (UnimplementedNodeGatewayServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedNodeGatewayServer) Connect(grpc.BidiStreamingServer[NodeMessage, PanelMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeGatewayServer) mustEmbedUnimplementedNodeGatewayServer() {}
func (UnimplementedNodeGatewayServer) testEmbeddedByValue()                     {}

// UnsafeNodeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeGatewayServer will
// result in compilation errors.
type UnsafeNodeGatewayServer interface {
	mustEmbedUnimplementedNodeGatewayServer()
}

func RegisterNodeGatewayServer(s grpc.ServiceRegistrar, srv NodeGatewayServer) {
	// If the following call panics, it indicates UnimplementedNodeGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeGateway_ServiceDesc, srv)
}

func _NodeGateway_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeGatewayServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeGateway_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeGatewayServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeGatewayServer).Connect(&grpc.GenericServerStream[NodeMessage, PanelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeGateway_ConnectServer = grpc.BidiStreamingServer[NodeMessage, PanelMessage]

// NodeGateway_ServiceDesc is the grpc.ServiceDesc for NodeGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vynel.node.v1.NodeGateway",
	HandlerType: (*NodeGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _NodeGateway_Join_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NodeGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vynel/node/v1/node.proto",
}
