// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vpn/node/v1/node.proto

// Panel <-> node protocol (docs/ARCHITECTURE.md §14).
// The node dials the panel; the panel pushes desired state, the node acknowledges.

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOp_Kind int32

const (
	UserOp_KIND_UNSPECIFIED UserOp_Kind = 0
	UserOp_KIND_UPSERT      UserOp_Kind = 1
	UserOp_KIND_REMOVE      UserOp_Kind = 2
)

// Enum value maps for UserOp_Kind.
var (
	UserOp_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_UPSERT",
		2: "KIND_REMOVE",
	}
	UserOp_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_UPSERT":      1,
		"KIND_REMOVE":      2,
	}
)

func (x UserOp_Kind) Enum() *UserOp_Kind {
	p := new(UserOp_Kind)
	*p = x
	return p
}

func (x UserOp_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOp_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (UserOp_Kind) Type() protoreflect.EnumType {
	return &file_vpn_node_v1_node_proto_enumTypes[0]
}

func (x UserOp_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOp_Kind.Descriptor instead.
func (UserOp_Kind) EnumDescriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{12, 0}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CsrDer        []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertDer       []byte                 `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	CaDer         []byte                 `protobuf:"bytes,2,opt,name=ca_der,json=caDer,proto3" json:"ca_der,omitempty"`
	NodeId        int64                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeCode      string                 `protobuf:"bytes,4,opt,name=node_code,json=nodeCode,proto3" json:"node_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *JoinResponse) GetCaDer() []byte {
	if x != nil {
		return x.CaDer
	}
	return nil
}

func (x *JoinResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *JoinResponse) GetNodeCode() string {
	if x != nil {
		return x.NodeCode
	}
	return ""
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*NodeMessage_Hello
	//	*NodeMessage_Ack
	//	*NodeMessage_Addresses
	Msg           isNodeMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetMsg() isNodeMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *NodeMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *NodeMessage) GetAddresses() *Addresses {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Addresses); ok {
			return x.Addresses
		}
	}
	return nil
}

type isNodeMessage_Msg interface {
	isNodeMessage_Msg()
}

type NodeMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type NodeMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type NodeMessage_Addresses struct {
	Addresses *Addresses `protobuf:"bytes,3,opt,name=addresses,proto3,oneof"`
}

func (*NodeMessage_Hello) isNodeMessage_Msg() {}

func (*NodeMessage_Ack) isNodeMessage_Msg() {}

func (*NodeMessage_Addresses) isNodeMessage_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	XrayVersion   string                 `protobuf:"bytes,2,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	AppliedHash   string                 `protobuf:"bytes,3,opt,name=applied_hash,json=appliedHash,proto3" json:"applied_hash,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *Hello) GetAppliedHash() string {
	if x != nil {
		return x.AppliedHash
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Primary       bool                   `protobuf:"varint,3,opt,name=primary,proto3" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Address) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Address) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

type Addresses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addresses) Reset() {
	*x = Addresses{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addresses) ProtoMessage() {}

func (x *Addresses) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addresses.ProtoReflect.Descriptor instead.
func (*Addresses) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *Addresses) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Ack confirms (or rejects) a snapshot or delta.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Ack) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PanelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PanelMessage_Snapshot
	//	*PanelMessage_Delta
	Msg           isPanelMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelMessage) Reset() {
	*x = PanelMessage{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelMessage) ProtoMessage() {}

func (x *PanelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelMessage.ProtoReflect.Descriptor instead.
func (*PanelMessage) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *PanelMessage) GetMsg() isPanelMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PanelMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Msg.(*PanelMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *PanelMessage) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Msg.(*PanelMessage_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

type isPanelMessage_Msg interface {
	isPanelMessage_Msg()
}

type PanelMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type PanelMessage_Delta struct {
	Delta *Delta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

func (*PanelMessage_Snapshot) isPanelMessage_Msg() {}

func (*PanelMessage_Delta) isPanelMessage_Msg() {}

// Snapshot is the full desired state: Xray config without clients plus users per inbound.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XrayConfig    []byte                 `protobuf:"bytes,3,opt,name=xray_config,json=xrayConfig,proto3" json:"xray_config,omitempty"`
	Inbounds      []*InboundUsers        `protobuf:"bytes,4,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *Snapshot) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Snapshot) GetXrayConfig() []byte {
	if x != nil {
		return x.XrayConfig
	}
	return nil
}

func (x *Snapshot) GetInbounds() []*InboundUsers {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type InboundUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Flow          string                 `protobuf:"bytes,3,opt,name=flow,proto3" json:"flow,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundUsers) Reset() {
	*x = InboundUsers{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundUsers) ProtoMessage() {}

func (x *InboundUsers) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundUsers.ProtoReflect.Descriptor instead.
func (*InboundUsers) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *InboundUsers) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundUsers) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InboundUsers) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *InboundUsers) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Delta changes users only; it applies on top of the state with hash base_hash.
type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	BaseHash      string                 `protobuf:"bytes,2,opt,name=base_hash,json=baseHash,proto3" json:"base_hash,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Ops           []*UserOp              `protobuf:"bytes,4,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *Delta) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Delta) GetBaseHash() string {
	if x != nil {
		return x.BaseHash
	}
	return ""
}

func (x *Delta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Delta) GetOps() []*UserOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type UserOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          UserOp_Kind            `protobuf:"varint,1,opt,name=kind,proto3,enum=vpn.node.v1.UserOp_Kind" json:"kind,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Flow          string                 `protobuf:"bytes,4,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOp) Reset() {
	*x = UserOp{}
	mi := &file_vpn_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOp) ProtoMessage() {}

func (x *UserOp) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOp.ProtoReflect.Descriptor instead.
func (*UserOp) Descriptor() ([]byte, []int) {
	return file_vpn_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *UserOp) GetKind() UserOp_Kind {
	if x != nil {
		return x.Kind
	}
	return UserOp_KIND_UNSPECIFIED
}

func (x *UserOp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UserOp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserOp) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

var File_vpn_node_v1_node_proto protoreflect.FileDescriptor

const file_vpn_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x16vpn/node/v1/node.proto\x12\vvpn.node.v1\"<\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\"v\n" +
	"\fJoinResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12\x15\n" +
	"\x06ca_der\x18\x02 \x01(\fR\x05caDer\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_code\x18\x04 \x01(\tR\bnodeCode\"\x9e\x01\n" +
	"\vNodeMessage\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.vpn.node.v1.HelloH\x00R\x05hello\x12$\n" +
	"\x03ack\x18\x02 \x01(\v2\x10.vpn.node.v1.AckH\x00R\x03ack\x126\n" +
	"\taddresses\x18\x03 \x01(\v2\x16.vpn.node.v1.AddressesH\x00R\taddressesB\x05\n" +
	"\x03msg\"\xca\x01\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12!\n" +
	"\fxray_version\x18\x02 \x01(\tR\vxrayVersion\x12!\n" +
	"\fapplied_hash\x18\x03 \x01(\tR\vappliedHash\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x122\n" +
	"\taddresses\x18\x06 \x03(\v2\x14.vpn.node.v1.AddressR\taddresses\"Q\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x18\n" +
	"\aprimary\x18\x03 \x01(\bR\aprimary\"?\n" +
	"\tAddresses\x122\n" +
	"\taddresses\x18\x01 \x03(\v2\x14.vpn.node.v1.AddressR\taddresses\"K\n" +
	"\x03Ack\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"v\n" +
	"\fPanelMessage\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x15.vpn.node.v1.SnapshotH\x00R\bsnapshot\x12*\n" +
	"\x05delta\x18\x02 \x01(\v2\x12.vpn.node.v1.DeltaH\x00R\x05deltaB\x05\n" +
	"\x03msg\"\x92\x01\n" +
	"\bSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1f\n" +
	"\vxray_config\x18\x03 \x01(\fR\n" +
	"xrayConfig\x125\n" +
	"\binbounds\x18\x04 \x03(\v2\x19.vpn.node.v1.InboundUsersR\binbounds\"y\n" +
	"\fInboundUsers\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04flow\x18\x03 \x01(\tR\x04flow\x12'\n" +
	"\x05users\x18\x04 \x03(\v2\x11.vpn.node.v1.UserR\x05users\",\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"{\n" +
	"\x05Delta\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1b\n" +
	"\tbase_hash\x18\x02 \x01(\tR\bbaseHash\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12%\n" +
	"\x03ops\x18\x04 \x03(\v2\x13.vpn.node.v1.UserOpR\x03ops\"\xc3\x01\n" +
	"\x06UserOp\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.vpn.node.v1.UserOp.KindR\x04kind\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12%\n" +
	"\x04user\x18\x03 \x01(\v2\x11.vpn.node.v1.UserR\x04user\x12\x12\n" +
	"\x04flow\x18\x04 \x01(\tR\x04flow\">\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vKIND_UPSERT\x10\x01\x12\x0f\n" +
	"\vKIND_REMOVE\x10\x022\x8e\x01\n" +
	"\vNodeGateway\x12;\n" +
	"\x04Join\x12\x18.vpn.node.v1.JoinRequest\x1a\x19.vpn.node.v1.JoinResponse\x12B\n" +
	"\aConnect\x12\x18.vpn.node.v1.NodeMessage\x1a\x19.vpn.node.v1.PanelMessage(\x010\x01B:Z8github.com/vyto4ka/vpn/internal/proto/vpn/node/v1;nodev1b\x06proto3"

var (
	file_vpn_node_v1_node_proto_rawDescOnce sync.Once
	file_vpn_node_v1_node_proto_rawDescData []byte
)

func file_vpn_node_v1_node_proto_rawDescGZIP() []byte {
	file_vpn_node_v1_node_proto_rawDescOnce.Do(func() {
		file_vpn_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_node_v1_node_proto_rawDesc), len(file_vpn_node_v1_node_proto_rawDesc)))
	})
	return file_vpn_node_v1_node_proto_rawDescData
}

var file_vpn_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vpn_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_vpn_node_v1_node_proto_goTypes = []any{
	(UserOp_Kind)(0),     // 0: vpn.node.v1.UserOp.Kind
	(*JoinRequest)(nil),  // 1: vpn.node.v1.JoinRequest
	(*JoinResponse)(nil), // 2: vpn.node.v1.JoinResponse
	(*NodeMessage)(nil),  // 3: vpn.node.v1.NodeMessage
	(*Hello)(nil),        // 4: vpn.node.v1.Hello
	(*Address)(nil),      // 5: vpn.node.v1.Address
	(*Addresses)(nil),    // 6: vpn.node.v1.Addresses
	(*Ack)(nil),          // 7: vpn.node.v1.Ack
	(*PanelMessage)(nil), // 8: vpn.node.v1.PanelMessage
	(*Snapshot)(nil),     // 9: vpn.node.v1.Snapshot
	(*InboundUsers)(nil), // 10: vpn.node.v1.InboundUsers
	(*User)(nil),         // 11: vpn.node.v1.User
	(*Delta)(nil),        // 12: vpn.node.v1.Delta
	(*UserOp)(nil),       // 13: vpn.node.v1.UserOp
}
var file_vpn_node_v1_node_proto_depIdxs = []int32{
	4,  // 0: vpn.node.v1.NodeMessage.hello:type_name -> vpn.node.v1.Hello
	7,  // 1: vpn.node.v1.NodeMessage.ack:type_name -> vpn.node.v1.Ack
	6,  // 2: vpn.node.v1.NodeMessage.addresses:type_name -> vpn.node.v1.Addresses
	5,  // 3: vpn.node.v1.Hello.addresses:type_name -> vpn.node.v1.Address
	5,  // 4: vpn.node.v1.Addresses.addresses:type_name -> vpn.node.v1.Address
	9,  // 5: vpn.node.v1.PanelMessage.snapshot:type_name -> vpn.node.v1.Snapshot
	12, // 6: vpn.node.v1.PanelMessage.delta:type_name -> vpn.node.v1.Delta
	10, // 7: vpn.node.v1.Snapshot.inbounds:type_name -> vpn.node.v1.InboundUsers
	11, // 8: vpn.node.v1.InboundUsers.users:type_name -> vpn.node.v1.User
	13, // 9: vpn.node.v1.Delta.ops:type_name -> vpn.node.v1.UserOp
	0,  // 10: vpn.node.v1.UserOp.kind:type_name -> vpn.node.v1.UserOp.Kind
	11, // 11: vpn.node.v1.UserOp.user:type_name -> vpn.node.v1.User
	1,  // 12: vpn.node.v1.NodeGateway.Join:input_type -> vpn.node.v1.JoinRequest
	3,  // 13: vpn.node.v1.NodeGateway.Connect:input_type -> vpn.node.v1.NodeMessage
	2,  // 14: vpn.node.v1.NodeGateway.Join:output_type -> vpn.node.v1.JoinResponse
	8,  // 15: vpn.node.v1.NodeGateway.Connect:output_type -> vpn.node.v1.PanelMessage
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_vpn_node_v1_node_proto_init() }
func file_vpn_node_v1_node_proto_init() {
	if File_vpn_node_v1_node_proto != nil {
		return
	}
	file_vpn_node_v1_node_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_Hello)(nil),
		(*NodeMessage_Ack)(nil),
		(*NodeMessage_Addresses)(nil),
	}
	file_vpn_node_v1_node_proto_msgTypes[7].OneofWrappers = []any{
		(*PanelMessage_Snapshot)(nil),
		(*PanelMessage_Delta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_node_v1_node_proto_rawDesc), len(file_vpn_node_v1_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpn_node_v1_node_proto_goTypes,
		DependencyIndexes: file_vpn_node_v1_node_proto_depIdxs,
		EnumInfos:         file_vpn_node_v1_node_proto_enumTypes,
		MessageInfos:      file_vpn_node_v1_node_proto_msgTypes,
	}.Build()
	File_vpn_node_v1_node_proto = out.File
	file_vpn_node_v1_node_proto_goTypes = nil
	file_vpn_node_v1_node_proto_depIdxs = nil
}
