// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vynnel/node/v1/node.proto

// Panel <-> node protocol (docs/ARCHITECTURE.md §14).
// The node dials the panel; the panel pushes desired state, the node acknowledges.

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOp_Kind int32

const (
	UserOp_KIND_UNSPECIFIED UserOp_Kind = 0
	UserOp_KIND_UPSERT      UserOp_Kind = 1
	UserOp_KIND_REMOVE      UserOp_Kind = 2
)

// Enum value maps for UserOp_Kind.
var (
	UserOp_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_UPSERT",
		2: "KIND_REMOVE",
	}
	UserOp_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_UPSERT":      1,
		"KIND_REMOVE":      2,
	}
)

func (x UserOp_Kind) Enum() *UserOp_Kind {
	p := new(UserOp_Kind)
	*p = x
	return p
}

func (x UserOp_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOp_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_vynnel_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (UserOp_Kind) Type() protoreflect.EnumType {
	return &file_vynnel_node_v1_node_proto_enumTypes[0]
}

func (x UserOp_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOp_Kind.Descriptor instead.
func (UserOp_Kind) EnumDescriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{17, 0}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CsrDer        []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertDer       []byte                 `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	CaDer         []byte                 `protobuf:"bytes,2,opt,name=ca_der,json=caDer,proto3" json:"ca_der,omitempty"`
	NodeId        int64                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeCode      string                 `protobuf:"bytes,4,opt,name=node_code,json=nodeCode,proto3" json:"node_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *JoinResponse) GetCaDer() []byte {
	if x != nil {
		return x.CaDer
	}
	return nil
}

func (x *JoinResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *JoinResponse) GetNodeCode() string {
	if x != nil {
		return x.NodeCode
	}
	return ""
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*NodeMessage_Hello
	//	*NodeMessage_Ack
	//	*NodeMessage_Addresses
	//	*NodeMessage_Stats
	Msg           isNodeMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMessage) GetMsg() isNodeMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *NodeMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *NodeMessage) GetAddresses() *Addresses {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Addresses); ok {
			return x.Addresses
		}
	}
	return nil
}

func (x *NodeMessage) GetStats() *StatsBatch {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isNodeMessage_Msg interface {
	isNodeMessage_Msg()
}

type NodeMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type NodeMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type NodeMessage_Addresses struct {
	Addresses *Addresses `protobuf:"bytes,3,opt,name=addresses,proto3,oneof"`
}

type NodeMessage_Stats struct {
	Stats *StatsBatch `protobuf:"bytes,4,opt,name=stats,proto3,oneof"`
}

func (*NodeMessage_Hello) isNodeMessage_Msg() {}

func (*NodeMessage_Ack) isNodeMessage_Msg() {}

func (*NodeMessage_Addresses) isNodeMessage_Msg() {}

func (*NodeMessage_Stats) isNodeMessage_Msg() {}

type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	XrayVersion  string                 `protobuf:"bytes,2,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	AppliedHash  string                 `protobuf:"bytes,3,opt,name=applied_hash,json=appliedHash,proto3" json:"applied_hash,omitempty"`
	Os           string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch         string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Addresses    []*Address             `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	CaddyVersion string                 `protobuf:"bytes,7,opt,name=caddy_version,json=caddyVersion,proto3" json:"caddy_version,omitempty"`
	// Host problems the panel should show: missing BBR, clock skew, no caddy binary...
	Warnings      []string `protobuf:"bytes,8,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *Hello) GetAppliedHash() string {
	if x != nil {
		return x.AppliedHash
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Hello) GetCaddyVersion() string {
	if x != nil {
		return x.CaddyVersion
	}
	return ""
}

func (x *Hello) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Primary       bool                   `protobuf:"varint,3,opt,name=primary,proto3" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *Address) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Address) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Address) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

type Addresses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addresses) Reset() {
	*x = Addresses{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addresses) ProtoMessage() {}

func (x *Addresses) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addresses.ProtoReflect.Descriptor instead.
func (*Addresses) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *Addresses) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// Ack confirms (or rejects) a snapshot or delta.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Ack) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PanelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PanelMessage_Snapshot
	//	*PanelMessage_Delta
	//	*PanelMessage_StatsAck
	Msg           isPanelMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelMessage) Reset() {
	*x = PanelMessage{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelMessage) ProtoMessage() {}

func (x *PanelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelMessage.ProtoReflect.Descriptor instead.
func (*PanelMessage) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *PanelMessage) GetMsg() isPanelMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PanelMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Msg.(*PanelMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *PanelMessage) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Msg.(*PanelMessage_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *PanelMessage) GetStatsAck() *StatsAck {
	if x != nil {
		if x, ok := x.Msg.(*PanelMessage_StatsAck); ok {
			return x.StatsAck
		}
	}
	return nil
}

type isPanelMessage_Msg interface {
	isPanelMessage_Msg()
}

type PanelMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type PanelMessage_Delta struct {
	Delta *Delta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type PanelMessage_StatsAck struct {
	StatsAck *StatsAck `protobuf:"bytes,3,opt,name=stats_ack,json=statsAck,proto3,oneof"`
}

func (*PanelMessage_Snapshot) isPanelMessage_Msg() {}

func (*PanelMessage_Delta) isPanelMessage_Msg() {}

func (*PanelMessage_StatsAck) isPanelMessage_Msg() {}

// StatsBatch carries counters collected since the previous batch. Batches are queued on the
// node and resent until acknowledged; (epoch, seq) makes ingestion idempotent.
type StatsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         string                 `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"` // random id of the node's queue; changes when the node state is reset
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Users         []*UserTraffic         `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	NodeUp        int64                  `protobuf:"varint,5,opt,name=node_up,json=nodeUp,proto3" json:"node_up,omitempty"`
	NodeDown      int64                  `protobuf:"varint,6,opt,name=node_down,json=nodeDown,proto3" json:"node_down,omitempty"`
	Online        []*OnlineUser          `protobuf:"bytes,7,rep,name=online,proto3" json:"online,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsBatch) Reset() {
	*x = StatsBatch{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsBatch) ProtoMessage() {}

func (x *StatsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsBatch.ProtoReflect.Descriptor instead.
func (*StatsBatch) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *StatsBatch) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *StatsBatch) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StatsBatch) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *StatsBatch) GetUsers() []*UserTraffic {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *StatsBatch) GetNodeUp() int64 {
	if x != nil {
		return x.NodeUp
	}
	return 0
}

func (x *StatsBatch) GetNodeDown() int64 {
	if x != nil {
		return x.NodeDown
	}
	return 0
}

func (x *StatsBatch) GetOnline() []*OnlineUser {
	if x != nil {
		return x.Online
	}
	return nil
}

func (x *StatsBatch) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UserTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Up            int64                  `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	Down          int64                  `protobuf:"varint,3,opt,name=down,proto3" json:"down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *UserTraffic) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserTraffic) GetUp() int64 {
	if x != nil {
		return x.Up
	}
	return 0
}

func (x *UserTraffic) GetDown() int64 {
	if x != nil {
		return x.Down
	}
	return 0
}

type OnlineUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ips           int32                  `protobuf:"varint,2,opt,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUser) Reset() {
	*x = OnlineUser{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUser) ProtoMessage() {}

func (x *OnlineUser) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUser.ProtoReflect.Descriptor instead.
func (*OnlineUser) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *OnlineUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OnlineUser) GetIps() int32 {
	if x != nil {
		return x.Ips
	}
	return 0
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"` // percent of all cores
	MemUsed       uint64                 `protobuf:"varint,2,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	MemTotal      uint64                 `protobuf:"varint,3,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	Load1         float64                `protobuf:"fixed64,4,opt,name=load1,proto3" json:"load1,omitempty"`
	RxBps         uint64                 `protobuf:"varint,5,opt,name=rx_bps,json=rxBps,proto3" json:"rx_bps,omitempty"`
	TxBps         uint64                 `protobuf:"varint,6,opt,name=tx_bps,json=txBps,proto3" json:"tx_bps,omitempty"`
	Uptime        uint64                 `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *Metrics) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Metrics) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *Metrics) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *Metrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Metrics) GetRxBps() uint64 {
	if x != nil {
		return x.RxBps
	}
	return 0
}

func (x *Metrics) GetTxBps() uint64 {
	if x != nil {
		return x.TxBps
	}
	return 0
}

func (x *Metrics) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type StatsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         string                 `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsAck) Reset() {
	*x = StatsAck{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsAck) ProtoMessage() {}

func (x *StatsAck) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsAck.ProtoReflect.Descriptor instead.
func (*StatsAck) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *StatsAck) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *StatsAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Snapshot is the full desired state: Xray config without clients plus users per inbound.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XrayConfig    []byte                 `protobuf:"bytes,3,opt,name=xray_config,json=xrayConfig,proto3" json:"xray_config,omitempty"`
	Inbounds      []*InboundUsers        `protobuf:"bytes,4,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	CaddyConfig   []byte                 `protobuf:"bytes,5,opt,name=caddy_config,json=caddyConfig,proto3" json:"caddy_config,omitempty"` // Caddy JSON config; empty = Caddy not needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *Snapshot) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Snapshot) GetXrayConfig() []byte {
	if x != nil {
		return x.XrayConfig
	}
	return nil
}

func (x *Snapshot) GetInbounds() []*InboundUsers {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *Snapshot) GetCaddyConfig() []byte {
	if x != nil {
		return x.CaddyConfig
	}
	return nil
}

type InboundUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Flow          string                 `protobuf:"bytes,3,opt,name=flow,proto3" json:"flow,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundUsers) Reset() {
	*x = InboundUsers{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundUsers) ProtoMessage() {}

func (x *InboundUsers) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundUsers.ProtoReflect.Descriptor instead.
func (*InboundUsers) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *InboundUsers) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundUsers) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InboundUsers) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *InboundUsers) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Delta changes users only; it applies on top of the state with hash base_hash.
type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	BaseHash      string                 `protobuf:"bytes,2,opt,name=base_hash,json=baseHash,proto3" json:"base_hash,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Ops           []*UserOp              `protobuf:"bytes,4,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{16}
}

func (x *Delta) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Delta) GetBaseHash() string {
	if x != nil {
		return x.BaseHash
	}
	return ""
}

func (x *Delta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Delta) GetOps() []*UserOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type UserOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          UserOp_Kind            `protobuf:"varint,1,opt,name=kind,proto3,enum=vynnel.node.v1.UserOp_Kind" json:"kind,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Flow          string                 `protobuf:"bytes,4,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOp) Reset() {
	*x = UserOp{}
	mi := &file_vynnel_node_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOp) ProtoMessage() {}

func (x *UserOp) ProtoReflect() protoreflect.Message {
	mi := &file_vynnel_node_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOp.ProtoReflect.Descriptor instead.
func (*UserOp) Descriptor() ([]byte, []int) {
	return file_vynnel_node_v1_node_proto_rawDescGZIP(), []int{17}
}

func (x *UserOp) GetKind() UserOp_Kind {
	if x != nil {
		return x.Kind
	}
	return UserOp_KIND_UNSPECIFIED
}

func (x *UserOp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UserOp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserOp) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

var File_vynnel_node_v1_node_proto protoreflect.FileDescriptor

const file_vynnel_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x19vynnel/node/v1/node.proto\x12\x0evynnel.node.v1\"<\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\"v\n" +
	"\fJoinResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12\x15\n" +
	"\x06ca_der\x18\x02 \x01(\fR\x05caDer\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\x12\x1b\n" +
	"\tnode_code\x18\x04 \x01(\tR\bnodeCode\"\xdb\x01\n" +
	"\vNodeMessage\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.vynnel.node.v1.HelloH\x00R\x05hello\x12'\n" +
	"\x03ack\x18\x02 \x01(\v2\x13.vynnel.node.v1.AckH\x00R\x03ack\x129\n" +
	"\taddresses\x18\x03 \x01(\v2\x19.vynnel.node.v1.AddressesH\x00R\taddresses\x122\n" +
	"\x05stats\x18\x04 \x01(\v2\x1a.vynnel.node.v1.StatsBatchH\x00R\x05statsB\x05\n" +
	"\x03msg\"\x8e\x02\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12!\n" +
	"\fxray_version\x18\x02 \x01(\tR\vxrayVersion\x12!\n" +
	"\fapplied_hash\x18\x03 \x01(\tR\vappliedHash\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x125\n" +
	"\taddresses\x18\x06 \x03(\v2\x17.vynnel.node.v1.AddressR\taddresses\x12#\n" +
	"\rcaddy_version\x18\a \x01(\tR\fcaddyVersion\x12\x1a\n" +
	"\bwarnings\x18\b \x03(\tR\bwarnings\"Q\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x18\n" +
	"\aprimary\x18\x03 \x01(\bR\aprimary\"B\n" +
	"\tAddresses\x125\n" +
	"\taddresses\x18\x01 \x03(\v2\x17.vynnel.node.v1.AddressR\taddresses\"K\n" +
	"\x03Ack\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb5\x01\n" +
	"\fPanelMessage\x126\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x18.vynnel.node.v1.SnapshotH\x00R\bsnapshot\x12-\n" +
	"\x05delta\x18\x02 \x01(\v2\x15.vynnel.node.v1.DeltaH\x00R\x05delta\x127\n" +
	"\tstats_ack\x18\x03 \x01(\v2\x18.vynnel.node.v1.StatsAckH\x00R\bstatsAckB\x05\n" +
	"\x03msg\"\x94\x02\n" +
	"\n" +
	"StatsBatch\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\tR\x05epoch\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x121\n" +
	"\x05users\x18\x04 \x03(\v2\x1b.vynnel.node.v1.UserTrafficR\x05users\x12\x17\n" +
	"\anode_up\x18\x05 \x01(\x03R\x06nodeUp\x12\x1b\n" +
	"\tnode_down\x18\x06 \x01(\x03R\bnodeDown\x122\n" +
	"\x06online\x18\a \x03(\v2\x1a.vynnel.node.v1.OnlineUserR\x06online\x121\n" +
	"\ametrics\x18\b \x01(\v2\x17.vynnel.node.v1.MetricsR\ametrics\"G\n" +
	"\vUserTraffic\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\x03R\x02up\x12\x12\n" +
	"\x04down\x18\x03 \x01(\x03R\x04down\"4\n" +
	"\n" +
	"OnlineUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03ips\x18\x02 \x01(\x05R\x03ips\"\xaf\x01\n" +
	"\aMetrics\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12\x19\n" +
	"\bmem_used\x18\x02 \x01(\x04R\amemUsed\x12\x1b\n" +
	"\tmem_total\x18\x03 \x01(\x04R\bmemTotal\x12\x14\n" +
	"\x05load1\x18\x04 \x01(\x01R\x05load1\x12\x15\n" +
	"\x06rx_bps\x18\x05 \x01(\x04R\x05rxBps\x12\x15\n" +
	"\x06tx_bps\x18\x06 \x01(\x04R\x05txBps\x12\x16\n" +
	"\x06uptime\x18\a \x01(\x04R\x06uptime\"2\n" +
	"\bStatsAck\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\tR\x05epoch\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\xb8\x01\n" +
	"\bSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1f\n" +
	"\vxray_config\x18\x03 \x01(\fR\n" +
	"xrayConfig\x128\n" +
	"\binbounds\x18\x04 \x03(\v2\x1c.vynnel.node.v1.InboundUsersR\binbounds\x12!\n" +
	"\fcaddy_config\x18\x05 \x01(\fR\vcaddyConfig\"|\n" +
	"\fInboundUsers\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04flow\x18\x03 \x01(\tR\x04flow\x12*\n" +
	"\x05users\x18\x04 \x03(\v2\x14.vynnel.node.v1.UserR\x05users\",\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"~\n" +
	"\x05Delta\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1b\n" +
	"\tbase_hash\x18\x02 \x01(\tR\bbaseHash\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12(\n" +
	"\x03ops\x18\x04 \x03(\v2\x16.vynnel.node.v1.UserOpR\x03ops\"\xc9\x01\n" +
	"\x06UserOp\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.vynnel.node.v1.UserOp.KindR\x04kind\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12(\n" +
	"\x04user\x18\x03 \x01(\v2\x14.vynnel.node.v1.UserR\x04user\x12\x12\n" +
	"\x04flow\x18\x04 \x01(\tR\x04flow\">\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vKIND_UPSERT\x10\x01\x12\x0f\n" +
	"\vKIND_REMOVE\x10\x022\x9a\x01\n" +
	"\vNodeGateway\x12A\n" +
	"\x04Join\x12\x1b.vynnel.node.v1.JoinRequest\x1a\x1c.vynnel.node.v1.JoinResponse\x12H\n" +
	"\aConnect\x12\x1b.vynnel.node.v1.NodeMessage\x1a\x1c.vynnel.node.v1.PanelMessage(\x010\x01B@Z>github.com/vyto4ka/vynnel/internal/proto/vynnel/node/v1;nodev1b\x06proto3"

var (
	file_vynnel_node_v1_node_proto_rawDescOnce sync.Once
	file_vynnel_node_v1_node_proto_rawDescData []byte
)

func file_vynnel_node_v1_node_proto_rawDescGZIP() []byte {
	file_vynnel_node_v1_node_proto_rawDescOnce.Do(func() {
		file_vynnel_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vynnel_node_v1_node_proto_rawDesc), len(file_vynnel_node_v1_node_proto_rawDesc)))
	})
	return file_vynnel_node_v1_node_proto_rawDescData
}

var file_vynnel_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vynnel_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_vynnel_node_v1_node_proto_goTypes = []any{
	(UserOp_Kind)(0),     // 0: vynnel.node.v1.UserOp.Kind
	(*JoinRequest)(nil),  // 1: vynnel.node.v1.JoinRequest
	(*JoinResponse)(nil), // 2: vynnel.node.v1.JoinResponse
	(*NodeMessage)(nil),  // 3: vynnel.node.v1.NodeMessage
	(*Hello)(nil),        // 4: vynnel.node.v1.Hello
	(*Address)(nil),      // 5: vynnel.node.v1.Address
	(*Addresses)(nil),    // 6: vynnel.node.v1.Addresses
	(*Ack)(nil),          // 7: vynnel.node.v1.Ack
	(*PanelMessage)(nil), // 8: vynnel.node.v1.PanelMessage
	(*StatsBatch)(nil),   // 9: vynnel.node.v1.StatsBatch
	(*UserTraffic)(nil),  // 10: vynnel.node.v1.UserTraffic
	(*OnlineUser)(nil),   // 11: vynnel.node.v1.OnlineUser
	(*Metrics)(nil),      // 12: vynnel.node.v1.Metrics
	(*StatsAck)(nil),     // 13: vynnel.node.v1.StatsAck
	(*Snapshot)(nil),     // 14: vynnel.node.v1.Snapshot
	(*InboundUsers)(nil), // 15: vynnel.node.v1.InboundUsers
	(*User)(nil),         // 16: vynnel.node.v1.User
	(*Delta)(nil),        // 17: vynnel.node.v1.Delta
	(*UserOp)(nil),       // 18: vynnel.node.v1.UserOp
}
var file_vynnel_node_v1_node_proto_depIdxs = []int32{
	4,  // 0: vynnel.node.v1.NodeMessage.hello:type_name -> vynnel.node.v1.Hello
	7,  // 1: vynnel.node.v1.NodeMessage.ack:type_name -> vynnel.node.v1.Ack
	6,  // 2: vynnel.node.v1.NodeMessage.addresses:type_name -> vynnel.node.v1.Addresses
	9,  // 3: vynnel.node.v1.NodeMessage.stats:type_name -> vynnel.node.v1.StatsBatch
	5,  // 4: vynnel.node.v1.Hello.addresses:type_name -> vynnel.node.v1.Address
	5,  // 5: vynnel.node.v1.Addresses.addresses:type_name -> vynnel.node.v1.Address
	14, // 6: vynnel.node.v1.PanelMessage.snapshot:type_name -> vynnel.node.v1.Snapshot
	17, // 7: vynnel.node.v1.PanelMessage.delta:type_name -> vynnel.node.v1.Delta
	13, // 8: vynnel.node.v1.PanelMessage.stats_ack:type_name -> vynnel.node.v1.StatsAck
	10, // 9: vynnel.node.v1.StatsBatch.users:type_name -> vynnel.node.v1.UserTraffic
	11, // 10: vynnel.node.v1.StatsBatch.online:type_name -> vynnel.node.v1.OnlineUser
	12, // 11: vynnel.node.v1.StatsBatch.metrics:type_name -> vynnel.node.v1.Metrics
	15, // 12: vynnel.node.v1.Snapshot.inbounds:type_name -> vynnel.node.v1.InboundUsers
	16, // 13: vynnel.node.v1.InboundUsers.users:type_name -> vynnel.node.v1.User
	18, // 14: vynnel.node.v1.Delta.ops:type_name -> vynnel.node.v1.UserOp
	0,  // 15: vynnel.node.v1.UserOp.kind:type_name -> vynnel.node.v1.UserOp.Kind
	16, // 16: vynnel.node.v1.UserOp.user:type_name -> vynnel.node.v1.User
	1,  // 17: vynnel.node.v1.NodeGateway.Join:input_type -> vynnel.node.v1.JoinRequest
	3,  // 18: vynnel.node.v1.NodeGateway.Connect:input_type -> vynnel.node.v1.NodeMessage
	2,  // 19: vynnel.node.v1.NodeGateway.Join:output_type -> vynnel.node.v1.JoinResponse
	8,  // 20: vynnel.node.v1.NodeGateway.Connect:output_type -> vynnel.node.v1.PanelMessage
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_vynnel_node_v1_node_proto_init() }
func file_vynnel_node_v1_node_proto_init() {
	if File_vynnel_node_v1_node_proto != nil {
		return
	}
	file_vynnel_node_v1_node_proto_msgTypes[2].OneofWrappers = []any{
		(*NodeMessage_Hello)(nil),
		(*NodeMessage_Ack)(nil),
		(*NodeMessage_Addresses)(nil),
		(*NodeMessage_Stats)(nil),
	}
	file_vynnel_node_v1_node_proto_msgTypes[7].OneofWrappers = []any{
		(*PanelMessage_Snapshot)(nil),
		(*PanelMessage_Delta)(nil),
		(*PanelMessage_StatsAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vynnel_node_v1_node_proto_rawDesc), len(file_vynnel_node_v1_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vynnel_node_v1_node_proto_goTypes,
		DependencyIndexes: file_vynnel_node_v1_node_proto_depIdxs,
		EnumInfos:         file_vynnel_node_v1_node_proto_enumTypes,
		MessageInfos:      file_vynnel_node_v1_node_proto_msgTypes,
	}.Build()
	File_vynnel_node_v1_node_proto = out.File
	file_vynnel_node_v1_node_proto_goTypes = nil
	file_vynnel_node_v1_node_proto_depIdxs = nil
}
